In [1]:
import pandas as pd
df = pd.read_csv('sumbelly.csv')
df

,week,Product_code,Product_name,Price_kg,date,halfpigprice,quota,Order,Part,CP,Betagro,Thaifoods
0,3,23057677.0,สามชั้นTT,220.0,1/20/2022,124.0,72576,82774,สามชั้น,220,190,214
1,4,23057677.0,สามชั้นTT,201.0,1/27/2022,117.0,70849,79094,สามชั้น,201,190,204
2,5,23057677.0,สามชั้นTT,191.0,2/3/2022,106.0,67821,68521,สามชั้น,191,180,194
3,6,23057677.0,สามชั้นTT,179.0,2/10/2022,100.0,44132,66944,สามชั้น,179,180,174
4,7,23057677.0,สามชั้นTT,167.0,2/17/2022,91.0,49522,71047,สามชั้น,167,165,166
5,8,23057677.0,สามชั้นTT,155.0,2/22/2022,90.0,51555,86008,สามชั้น,155,155,166
6,9,23057677.0,สามชั้นTT,155.0,3/1/2022,90.0,54676,88928,สามชั้น,150,160,166
7,10,23057677.0,สามชั้นTT,154.0,3/9/2022,95.0,55856,122098,สามชั้น,154,163,172
8,11,23057677.0,สามชั้นTT,157.0,3/17/2022,97.0,70887,135281,สามชั้น,157,165,169
9,12,23057677.0,สามชั้นTT,157.0,3/24/2022,98.0,97742,143491,สามชั้น,157,165,169
10,13,23057677.0,สามชั้นTT,165.0,3/31/2022,99.0,111534,134206,สามชั้น,166,167,169
11,14,23057677.0,สามชั้นTT,170.0,4/7/2022,104.0,100815,146728,สามชั้น,171,170,174
12,15,23057677.0,สามชั้นTT,174.0,4/11/2022,105.0,122952,115788,สามชั้น,177,174,174
13,16,23057677.0,สามชั้นTT,176.0,4/21/2022,109.0,108950,98273,สามชั้น,177,174,174
14,17,23057677.0,สามชั้นTT,183.0,4/28/2022,111.0,99242,99544,สามชั้น,185,176,178
15,18,23057677.0,สามชั้นTT,185.0,5/5/2022,114.0,86721,92782,สามชั้น,185,178,181
16,19,23057677.0,สามชั้นTT,195.0,5/12/2022,120.0,92500,88399,สามชั้น,195,183,184
17,20,23057677.0,สามชั้นTT,197.0,5/19/2022,123.0,91449,84762,สามชั้น,197,186,184
18,21,23057677.0,สามชั้นTT,197.0,5/26/2022,125.0,80711,83364,สามชั้น,197,192,186
19,22,23057677.0,สามชั้นTT,199.0,2/6/2022,127.0,74335,85004,สามชั้น,199,193,186
20,23,NaN,NaN,NaN,NaN,NaN,88442,46174,สามชั้น,196,193,186